# Site

name: "The Silent Sexism Project"
description: "Let’s Fight Sexism Together by sharing our experiences and addressing the silent threat. Because no matter how small the instance, your voice matters!"
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
hero: 'assets/images/jumbotron.jpg'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  
  amrita:
    name: Amrita Nair
    display_name: Amrita Nair
    avatar: 'assets/images/amrita1.jpg'
    email: 
    instagram:
    twitter: 
    description: "test test test"
  
  pooja:
    name: Pooja Kadaboina
    display_name: Pooja Kadaboina
    avatar: 'assets/images/pooja1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""
  
  trupthi:
    name: Trupthi Chandan
    display_name: Trupthi Chandan
    avatar: 'assets/images/trupthi1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""
  
  lily:
    name: Lily Ann
    display_name: Lily Ann
    avatar: 'assets/images/lily1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""
  
  roheet:
    name: Roheet Bose
    display_name: Roheet Bose
    avatar: 'assets/images/roheet1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""

  manasa:
    name: Manasa H.M
    display_name: Manasa H.M
    avatar: 'assets/images/manasa1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""
  
  rachel:
    name: Rachel Jacob T.
    display_name: Rachel Jacob T.  
    avatar: 'assets/images/rachel1.jpg'
    email: 
    instagram: 
    twitter: 
    description: ""

  drishti:
    name: Drishti Sahay
    display_name: Drishti Sahay
    avatar: 'assets/images/drishti1.jpg'
    email: 
    instagram: 
    twitter:
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]


